# Setup
title:        Oxygen
tagline:      A blog by Thawsitt
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Thawsitt Naing
  url:        https://thawsitt.me 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    #css_class: 'codehilite'
    css_class: 'highlight'
